### PR TITLE
Add Node.js domains support

### PR DESCRIPTION
**Pull request by xaka**
A connection pool acts as a resource manager and for users such
operations as `acquire` and `release` should behave as `new` and
`delete`. That means, if domains are involved, acquired resources should
be reassigned to an active domain which is a `process.domain` at the
time of `acquire` request, not response. The opposite operation should
also happen when resource is being released, it should be unassigned
from its domain if such exists.

### CODE REVIEW

**Comment by xaka** [comment]
BTW, i had to run the test file through JS formatter as there were a lot of different styles mixed together. If you would prefer to see the result of formatting as a separate PR or to not see it at all, let me know and i'll update this one.

**Comment by xaka** [comment]
Another topic that i wanted to raise is a callbacks calling. The way it happens right now is very dangerous because callback calls are not being passed to a next event loop iteration (via `nextTick` or `setTimeout`) and happen right here and right now. Such behavior usually leads to situations that are pretty difficult to debug.

Right now ...:

``` javascript
function acquire(callback) {
  ...
  callback(...)
  ...
}
```

... but should be:

``` javascript
function acquire(callback) {
  ...
  process.nextTick(function() {
    callback(...);
  });
  ...
}
```

**Comment by tgriesser** [comment]
Cool maybe that second issue you just raised could be fixed in a separate ticket.

Does it make sense to check whether the object is actually an `instanceof EventEmitter` before adding to the domain?

**Comment by xaka** [comment]
I think you're right, there is no reason to apply the logic to objects that are not `EvenEmitter` based. The PR has been updated accordingly.

**Comment by xaka** [comment]
@tgriesser as there were no domains in 0.6, tests fail. how much do you care about 0.6?

**Comment by tgriesser** [comment]
Not at all, feel free to take that out of the travis and I'll merge.

**Comment by xaka** [comment]
Yay! What about `knex`? What's the plan?

**Comment by xaka** [comment]
@tgriesser I'll double-check whether this PR had introduced any memory leaks, I hope it didn't :)

**Pull request merged**
